repos:
- repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
  hooks:
  - id: seed-isort-config
    args: [--application-directories, src]
- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
    args: [--safe, --quiet]
    language_version: python3.6
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
  - id: flake8
- repo: https://github.com/asottile/pyupgrade
  rev: v3.18.0
  hooks:
  - id: pyupgrade
